
package Vista;

import Controlador.Controlador_FRM_Usuario;

public class FRM_Usuario extends javax.swing.JFrame {

    Controlador_FRM_Usuario controlador;
    public FRM_Usuario() {
        initComponents();
          setLocation(250,150);
        controlador= new Controlador_FRM_Usuario(this);
       this.gUI_InformacionUsuario1.agregarControlador(controlador);
       this.gUI_Botones1.agregarEventos(controlador);
        estadoInicio();
    }

    public void agregar(){
        this.gUI_Botones1.habilitarAgregar();
        this.gUI_InformacionUsuario1.habilitar();
    }
    public String devolverNombreU(){
      return  this.gUI_InformacionUsuario1.devolverNombreUsuario();
    }
public void modificarEliminar(){
    this.gUI_Botones1.habilitarExistencia();
    this.gUI_InformacionUsuario1.habilitar();
}
public void mostrarInformacion(String arreglo[]){
    this.gUI_InformacionUsuario1.mostrarInfo(arreglo);
}
public String[]  informacion(){
   return this.gUI_InformacionUsuario1.devolverInformacion();
}
public void limpiarVentana(){
    this.gUI_InformacionUsuario1.limpiarIntefaz();
}
public void estadoInicio(){
    this.gUI_InformacionUsuario1.estadoInicial();
    this.gUI_Botones1.estadoInicial();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_InformacionUsuario1 = new Vista.GUI_InformacionUsuario();
        gUI_Botones1 = new Vista.GUI_Botones();
        jl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(gUI_InformacionUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 437, 328));
        getContentPane().add(gUI_Botones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoU.png"))); // NOI18N
        getContentPane().add(jl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
           controlador.agregarInformacionCuandoCierraVentana();
        //controladorP.cierreUsuario();
        
    }//GEN-LAST:event_formComponentHidden

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_InformacionUsuario gUI_InformacionUsuario1;
    private javax.swing.JLabel jl_Fondo;
    // End of variables declaration//GEN-END:variables
}
