/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MenuPrincipal;

/**
 *
 * @author Marianghel
 */
public class FRM_FuenteInformacion extends javax.swing.JFrame {

    /**
     * Creates new form FRM_FuenteInformacion
     */
    Controlador_FRM_MenuPrincipal controladorP;
    public FRM_FuenteInformacion(Controlador_FRM_MenuPrincipal controladorP) {
        initComponents();
        setLocation(270,150);
        this.gUI_InformacionFuente1.agregarEvento(controladorP);
        this.gUI_InformacionFuente1.agregarControlador(controladorP);
    }

    public void mensajeOpcion(){
        this.gUI_InformacionFuente1.mensaje();
    }
    public boolean devolverArchivo(){
      return this.gUI_InformacionFuente1.opcionArchivo();
    }
    public boolean devolverBD(){
      return  this.gUI_InformacionFuente1.opcionBaseDatos();
        
    }
    public boolean devolverXML(){
       return this.gUI_InformacionFuente1.opcionXML();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_InformacionFuente1 = new Vista.GUI_InformacionFuente();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_InformacionFuente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_InformacionFuente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_InformacionFuente gUI_InformacionFuente1;
    // End of variables declaration//GEN-END:variables
}
