
package Vista;

import Controlador.Controlador_FRM_Estudiantes;
import Controlador.Controlador_FRM_Matricula;
import Controlador.Controlador_FRM_Usuario;

public class GUI_InformacionEstudiantes extends javax.swing.JPanel {

    
    Controlador_FRM_Estudiantes controlador;
    public GUI_InformacionEstudiantes() {
        initComponents(); 
    }
    public void agregarControlador(Controlador_FRM_Estudiantes controlador)
    {
        this.controlador=controlador; 
    }
    public String[] devolverInformacion()
    {
        String arreglo[];
        arreglo=new String[3];
        arreglo[0]=this.jt_Cedula.getText();
        arreglo[1]=this.jt_NombreCompleto.getText();
        arreglo[2]=this.jt_Direccion.getText();
        
        return arreglo;
    }
    public String devolverCedula()
    {
        return this.jt_Cedula.getText();
    }
     public String devolverNombre()
    {
        return this.jt_NombreCompleto.getText();
    }
     public String devolverDireccion(){
         return this.jt_Direccion.getText();
     }
    public void mostrarInformacion(String arreglo[])
    {
        this.jt_NombreCompleto.setText(arreglo[1]);
        this.jt_Direccion.setText(arreglo[2]);
    }
    
     public void agregarEventos(Controlador_FRM_Estudiantes controlador)
    {
        this.controlador=controlador;
        this.btn_Consulta.addActionListener(controlador);
    }
        public void limpiarInterfaz(){
    this.jt_Cedula.setText("");
    this.jt_NombreCompleto.setText("");
    this.jt_Direccion.setText("");
}
    public void estadoInicial(){
    this.jt_Cedula.setEnabled(true);
    this.jt_NombreCompleto.setEnabled(false);
    this.jt_Direccion.setEnabled(false);
}
    public void hablilitarSiExiste(){
    this.jt_Cedula.setEnabled(false);
    this.jt_NombreCompleto.setEnabled(true);
    this.jt_Direccion.setEnabled(true);
}
    public void habilitarNoExiste(){
    this.jt_Cedula.setEnabled(true);
    this.jt_NombreCompleto.setEnabled(true);
    this.jt_Direccion.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Cedula = new javax.swing.JLabel();
        jl_NombreCompleto = new javax.swing.JLabel();
        jl_Direccion = new javax.swing.JLabel();
        jt_Cedula = new javax.swing.JTextField();
        jt_NombreCompleto = new javax.swing.JTextField();
        jt_Direccion = new javax.swing.JTextField();
        btn_Consulta = new javax.swing.JButton();

        jl_Cedula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_Cedula.setText("Cédula:");

        jl_NombreCompleto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_NombreCompleto.setText("Nombre Completo:");

        jl_Direccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_Direccion.setText("Dirección:");

        jt_Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_CedulaKeyPressed(evt);
            }
        });

        btn_Consulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar.png"))); // NOI18N
        btn_Consulta.setActionCommand("Consulta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Direccion)
                    .addComponent(jl_NombreCompleto)
                    .addComponent(jl_Cedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btn_Consulta))
                    .addComponent(jt_NombreCompleto)
                    .addComponent(jt_Direccion))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Consulta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jl_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NombreCompleto)
                    .addComponent(jt_NombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Direccion))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_CedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_CedulaKeyPressed
        if(evt.getKeyCode()==10){
            controlador.buscar();
        }
    }//GEN-LAST:event_jt_CedulaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Consulta;
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_Direccion;
    private javax.swing.JLabel jl_NombreCompleto;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_Direccion;
    private javax.swing.JTextField jt_NombreCompleto;
    // End of variables declaration//GEN-END:variables
}
