/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Marianghel
 */
public class GUI_InformacionFuente extends javax.swing.JPanel {

    /**
     * Creates new form GUI_InformacionFuente
     */
    public GUI_InformacionFuente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Titulo = new javax.swing.JLabel();
        rbtn_Archivo = new javax.swing.JRadioButton();
        rbtn_Base = new javax.swing.JRadioButton();
        rbtn_xml = new javax.swing.JRadioButton();

        jl_Titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_Titulo.setText("Fuente Información");

        rbtn_Archivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbtn_Archivo.setText("Archivo plano");

        rbtn_Base.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbtn_Base.setText("Base de datos");

        rbtn_xml.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbtn_xml.setText("XML");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jl_Titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(rbtn_Archivo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtn_Base)
                            .addComponent(rbtn_xml))))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jl_Titulo)
                .addGap(40, 40, 40)
                .addComponent(rbtn_Archivo)
                .addGap(40, 40, 40)
                .addComponent(rbtn_Base)
                .addGap(40, 40, 40)
                .addComponent(rbtn_xml)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_Titulo;
    private javax.swing.JRadioButton rbtn_Archivo;
    private javax.swing.JRadioButton rbtn_Base;
    private javax.swing.JRadioButton rbtn_xml;
    // End of variables declaration//GEN-END:variables
}
