/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Usuario;

/**
 *
 * @author Marianghel
 */
public class GUI_InformacionUsuario extends javax.swing.JPanel {

    /**
     * Creates new form GUI_InformacionUsuario
     */
    Controlador_FRM_Usuario controlador;
    public GUI_InformacionUsuario() {
        initComponents();
        cargarTipo();
    }

    public void agregarControlador(Controlador_FRM_Usuario controlador)
    {
        this.controlador=controlador;
        
        }
    public String[] devolverInformacion(){
    String arreglo[];
    arreglo=new String[4];
    arreglo[0]=this.jt_NombreC.getText();
    arreglo[1]=this.jt_NombreU.getText();
    arreglo[2]=this.jt_Contrasena.getText();
    arreglo[3]=""+this.jcb_Tipo.getSelectedIndex();
    return arreglo;
    }
public void limpiarIntefaz(){
    this.jt_NombreC.setText("");
    this.jt_NombreU.setText("");
    this.jt_Contrasena.setText("");
}
public void cargarTipo(){
    this.jcb_Tipo.removeAllItems();
   for(int contador=0;contador<1;contador++){
        this.jcb_Tipo.addItem("Administrador");
        this.jcb_Tipo.addItem("Visitante");
    }
    this.jcb_Tipo.setSelectedIndex(1);
}
public void mostrarInfo(String arreglo[]){
    this.jt_NombreC.setText(arreglo[0]);
    this.jt_NombreU.setText(arreglo[1]);
    this.jt_Contrasena.setText(arreglo[2]);
    this.jcb_Tipo.setSelectedIndex(Integer.parseInt(arreglo[3]));
}
public String devolverNombreUsuario(){
    return this.jt_NombreU.getText();
}
public void estadoInicial(){
    this.jt_NombreC.setEnabled(false);
    this.jt_NombreU.setEnabled(true);
    this.jt_Contrasena.setEnabled(false);
    this.jcb_Tipo.setEnabled(false);
}
public void habilitar(){
    this.jt_NombreC.setEnabled(true);
    this.jt_NombreU.setEnabled(true);
    this.jt_Contrasena.setEnabled(true);
    this.jcb_Tipo.setEnabled(true);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jl_NombreC = new javax.swing.JLabel();
        jl_Contrasena = new javax.swing.JLabel();
        jl_Tipo = new javax.swing.JLabel();
        jt_NombreU = new javax.swing.JTextField();
        jt_NombreC = new javax.swing.JTextField();
        jcb_Tipo = new javax.swing.JComboBox<>();
        jt_Contrasena = new javax.swing.JPasswordField();

        jl_Titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_Titulo.setText("Registro Usuario");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre Usuario");

        jl_NombreC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_NombreC.setText("Nombre completo");

        jl_Contrasena.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_Contrasena.setText("Contraseña");

        jl_Tipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_Tipo.setText("Tipo usuario");

        jt_NombreU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_NombreUKeyPressed(evt);
            }
        });

        jcb_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jl_Titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jl_NombreC)
                            .addComponent(jl_Contrasena)
                            .addComponent(jl_Tipo))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_NombreU)
                            .addComponent(jt_NombreC)
                            .addComponent(jt_Contrasena)
                            .addComponent(jcb_Tipo, 0, 162, Short.MAX_VALUE))))
                .addGap(38, 78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jl_Titulo)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_NombreU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_NombreC)
                    .addComponent(jt_NombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Contrasena)
                    .addComponent(jt_Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Tipo)
                    .addComponent(jcb_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_NombreUKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_NombreUKeyPressed
          if(evt.getKeyCode()==10){
            controlador.buscar();
        }
    }//GEN-LAST:event_jt_NombreUKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jcb_Tipo;
    private javax.swing.JLabel jl_Contrasena;
    private javax.swing.JLabel jl_NombreC;
    private javax.swing.JLabel jl_Tipo;
    private javax.swing.JLabel jl_Titulo;
    private javax.swing.JPasswordField jt_Contrasena;
    private javax.swing.JTextField jt_NombreC;
    private javax.swing.JTextField jt_NombreU;
    // End of variables declaration//GEN-END:variables
}
