
package Vista;

import Controlador.Controlador_FRM_MenuPrincipal;

public class GUI_InformacionLogin extends javax.swing.JPanel {

    Controlador_FRM_MenuPrincipal controladorP;
    public GUI_InformacionLogin() {
        initComponents();
          this.controladorP=controladorP;
    }
    public void agregarControladorPrincipal(Controlador_FRM_MenuPrincipal controlador){
        this.controladorP=controlador;
    }
    public String[] devolverInformacion(){
        String arreglo[]= new String [2];
        arreglo[0]=this.jt_NombreUsuario.getText();
        arreglo[1]=this.jt_Contrasena.getText();
        return arreglo;
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Titulo = new javax.swing.JLabel();
        jl_NombreUsuario = new javax.swing.JLabel();
        jl_Contrasena = new javax.swing.JLabel();
        jt_NombreUsuario = new javax.swing.JTextField();
        jt_Contrasena = new javax.swing.JPasswordField();

        jl_Titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_Titulo.setText("Login");

        jl_NombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_NombreUsuario.setText("Nombre Usuario");

        jl_Contrasena.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_Contrasena.setText("Contraseña");

        jt_NombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_NombreUsuarioKeyPressed(evt);
            }
        });

        jt_Contrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_ContrasenaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_NombreUsuario)
                    .addComponent(jl_Contrasena))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_Titulo)
                    .addComponent(jt_NombreUsuario)
                    .addComponent(jt_Contrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jl_Titulo)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NombreUsuario)
                    .addComponent(jt_NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Contrasena)
                    .addComponent(jt_Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_NombreUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_NombreUsuarioKeyPressed
        if(evt.getKeyCode()==10){
            controladorP.confirmandoUsuario(devolverInformacion()); 
        }
    }//GEN-LAST:event_jt_NombreUsuarioKeyPressed

    private void jt_ContrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_ContrasenaKeyPressed
        if(evt.getKeyCode()==10){
            controladorP.confirmandoUsuario(devolverInformacion());
        }
    }//GEN-LAST:event_jt_ContrasenaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_Contrasena;
    private javax.swing.JLabel jl_NombreUsuario;
    private javax.swing.JLabel jl_Titulo;
    private javax.swing.JPasswordField jt_Contrasena;
    private javax.swing.JTextField jt_NombreUsuario;
    // End of variables declaration//GEN-END:variables
}
